#!/usr/bin/env python

""" my_kinetics_adapter

Usage:
    my_kinetics_adapter
            [--videos_per_chunk <videos_per_chunk>]
            [--num_workers <num_workers>]
            [--shm_dir_path <shm_dir_path>]
            [--frame_size <frame_size>]
            [--shuffle <shuffle>]
            <list_file>
            <output_folder>


Options:
    --shuffle=<shuffle>    [default: False]
    --frame_size=<frame_size>    [default: -1]
    --shm_dir_path=<shm_dir_path>    [default: /dev/shm]
    --videos_per_chunk=<videos_per_chunk>    [default: 100]
    --num_workers=<num_workers>    [default: 4]
    """


from docopt import docopt
from gulpio.adapters import MyKineticsAdapter
from gulpio.fileio import GulpIngestor

if __name__ == "__main__":
    arguments = docopt(__doc__)
    print(arguments)

    shm_dir_path = arguments['--shm_dir_path']
    frame_size = int(arguments['--frame_size'])
    shuffle = arguments['--shuffle']
    list_file = arguments['<list_file>']
    output_folder = arguments['<output_folder>']
    videos_per_chunk = int(arguments['--videos_per_chunk'])
    num_workers = int(arguments['--num_workers'])
    adapter = MyKineticsAdapter(
        list_file,
        shuffle,
        frame_size,
        shm_dir_path,
        )
ingestor = GulpIngestor(adapter,
                        output_folder,
                        videos_per_chunk,
                        num_workers)
ingestor()
